backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

local_backend: true

media_folder: public/img/config
public_folder: /img/config

collections:
  - name: "siteconfig"
    label: "Site Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "navbar"
        label: "Navbar"
        file: "content/metadata/config/navbar.json"
        fields:
          - name: "logo"
            label: "Brand logo"
            hint: "The logo that appears in the left-most side of the navbar"
            widget: image
          - name: "links"
            label: "Links"
            widget: list
            fields:
              - name: "text"
                label: "Link text"
                hint: "The text you want displayed for the link"
                widget: string
              - name: "url"
                label: "URL"
                widget: string
      - name: "footer"
        label: "Footer"
        file: "content/metadata/config/footer.json"
        fields:
          - name: "logo"
            label: "Brand logo"
            hint: "The logo that appears in the middle of the footer. Falls back to brand text if populated."
            widget: image
            required: false
          - name: "brandtext"
            label: "Brand text"
            hint: "The brand text that appears in the middle of the footer. Defaults to brand logo if populated."
            widget: image
            required: false
          - name: "footertext"
            label: "Footer description"
            hint: "The text that appears below the footer text. Optional."
            widget: string
          - name: "links"
            label: "Links"
            widget: list
            fields:
              - name: "text"
                label: "Link text"
                hint: "The text you want displayed for the link"
                widget: string
              - name: "url"
                label: "URL"
                widget: string
              - name: "class"
                label: "MDI Icon Name"
                hint: "Name of the Material Design Icon you want to appear as the link icon. Visit https://materialdesignicons.com to find icons. For example, the name you would enter for this icon would be 'currency-thb': (https://materialdesignicons.com/icon/currency-thb)."
  - name: "staticpages"
    label: "Static Pages"
    delete: false
    editor:
      preview: false
    files:
      - name: "home"
        label: "Home"
        file: "content/metadata/pages/home.json"
        fields:
          - name: "header"
            label: "Header"
            hint: "The big text."
            widget: string
      - name: "about"
        label: "About Page"
        file: "content/metadata/about.json"
        fields:
          - name: "header"
            label: "Header"
            hint: "The big text above the body text."
            widget: string
